### ISSUE TITLE
Extended math support

### ISSUE THREAD

**Issue by bennyboer** [bennyboer/thaw#22]
Extend the math support by supporting more MathML elements.
This is a follow up issue for the initial math support implemented in #16.

## Tasks
- [ ] Support units in the attribute values (for example `mm`, `px`, `cm`, `em`, ..)
- [ ] Table support
  - [ ] `<mtable>` element
  - [ ] `<mtr>` element
  - [ ] `<mtd>` element
- [ ] `<menclose>` support
- [ ] `<maligngroup>` and `<malignmark>` support
- [ ] `<merror>` support
- [ ] `<mfenced>` support
- [ ] `<mphantom>` support
- [ ] Full `<mo>` support
  - [ ] Support for displaying large operators (parenthesis, brackets, sum, product, ...) - Attribute `largeop`
  - [ ] Attribute `maxsize`
  - [ ] Attribute `minsize`
- [ ] `mstyle` support

If #23 is already done before working on these tasks, the LaTeX to MathML converter needs to be adjusted as well!
