### ISSUE TITLE
Use Citeproc for citation styles

### ISSUE THREAD

**Issue by bennyboer** [bennyboer/thaw#35]
We could use something like [citeproc-java](https://github.com/michel-kraemer/citeproc-java) to support a lot of citation styles without a lot more work!

**Comment by bennyboer** [comment]
During testing I found that this will lead to a vast performance loss when building the document. We need to introduce some kind of caching for already built stuff (when the literature source file *.tdr) has not changed.

**Comment by bennyboer** [comment]
# TODO

- [x] New attribute the the info file: `bibliography` where the value is a bibliography file (supporting **BibTex, EndNote and RIS** (supported by citeproc-java)).
- [x] Loading bibliography file (from info file) for citeproc-java using a new generic citation style class (CSLCitationStyle maybe?).
- [x] Using the new CSLCitationStyle class for citations and generating bibliography leveraging citeproc-java
- [x] Caching
  - [x] Cache already generated citations and the previous bibliography in the user folder under `~/.thaw/cache/citation/` -> only regenerate when really needed to save time
  - [x] When bibliography file is changed -> Update cached bibliography
  - [x] When a new source is referenced using the `#CITE#` thingy (not yet in the bibliography!) -> Update cached bibliography, but do not regenerate the already used citation strings (only the new one)
  - [x] When an already existing source is referenced using the `#CITE#` thingy (already in bibliography) -> Do not update cached bibliography, generate **only** the new citation string for the thingy

**Comment by bennyboer** [comment]
Estimated to be done by 18th of September

**Comment by bennyboer** [comment]
# Example

### Info file:
```
encoding = UTF-8
language = en

bibliography.file = refs.bib
bibliography.style = apa
```

### Bibtex file (refs.bib)
```
@INPROCEEDINGS{Shor,
    author = {P. W. {Shor}},
    booktitle = {Proceedings 35th Annual Symposium on Foundations of Computer Science},
    title = {Algorithms for quantum computation: discrete logarithms and factoring},
    year = {1994},
    pages = {124-134} }
```

### Thaw document text file (*.tdt)
```
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, 
sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, 
sed diam voluptua #CITE, 'Shor, locator=page 124'#.

#REFERENCES#
```

### Result (Screenshot)
![grafik](https://user-images.githubusercontent.com/14014633/93028327-779fe300-f613-11ea-8c9c-ce35b8c2e7a4.png)
