### ISSUE TITLE
Support Markdown as input format

### ISSUE THREAD

**Issue by bennyboer** [bennyboer/thaw#49]
Certainly you might have existing Markdown documents that you want to convert into PDFs or don't want to use the Thaw document text format since you don't need most of the more elaborate features.

Thus we could allow specifying markdown files as text file format instead of *.tdt files.

This should be a configuration option in the *.tdi file:

### TDI file
```
encoding = UTF-8
text-file-format = md // Default value is tdt
```

When specifying `md` as value for the `text-file-format` key, Thaw should look for `*.md` files in the project folders instead of `*.tdt` files. We need to provide a separate converter to the Thaw document text format tree for it to work properly.

### TODO
- [ ] Introduce new key `text-file-format` and values `md`, `tdt` to the Thaw info model
- [ ] Implement converter from markdown files to the Thaw document text format tree
  - [ ] Use existing markdown parser library to provide the extension faster
  - [ ] Map HTML tree the markdown parser probably produces to the Thaw document text format tree
  - [ ] Unit tests
- [ ] Update documentation
