### ISSUE TITLE
Write own CSL implementation

### ISSUE THREAD

**Issue by bennyboer** [bennyboer/thaw#63]
Since the current library citeproc-java uses JavaScript to run, it it slow and we cannot really build using JLink or jpackage. Thus we have to write our own implementation using pure Java.

CSL v1.0.1 specification to implement: https://docs.citationstyles.org/en/1.0.1/specification.html

This unforeseen problem will probably delay `v0.1` a little.

Development branch: `csl`

# TO-DO

- [ ] Remove `citeproc-java` notice in the third party document
- [ ] Add attribution notice for Jackson XML (https://github.com/FasterXML/jackson-dataformat-xml)
- [ ] Do not include the styles and locale jars in the built binary - instead load them on-demand from the GitHub repositories when thaw is first started (due to licensing problems)
- [ ] Add attribution notice to satisfy the citationstyle language assets license https://creativecommons.org/licenses/by-sa/3.0/

**Comment by bennyboer** [comment]
Blocked until #65 is done.
